### PR TITLE
Fix amp clientid prefix on non amp site

### LINKED ISSUE #7: Instead of regex just use str_replace to extract CLIENT_ID
Instead of regex just use str_replace like this - see this - https://github.com/rtCamp/rtcamp-v9/pull/354

_Originally posted by @pradeep910 in https://github.com/rtCamp/rthistory-with-ga/pull/6/review_comment/create_

### PR DESCRIPTION
**Pull request by sagarnasit**
Fixes #7 

Handled caveat mentioned here https://github.com/rtCamp/rtcamp-v9/pull/354#issue-354154064

### CODE REVIEW

File: rthistory-with-ga.php [hunk 1]
```diff
@@ -46,17 +46,30 @@ function rtga_pass_clientid_in_gravity_form( $entry, $form ) {
...
+		// Get clientid without GA prefix.
+		if ( preg_match( $regex, $_COOKIE['_ga'], $match ) ) {
+			$client_id  = $match[0];
+			$amp_prefix = 'amp-';
+
+			// Find clientid starting position with amp prefix.
+			$position = strpos( $client_id, $amp_prefix );
+			if ( false !== $position ) {
+				// Extract clientid.
+				$client_id = substr( $client_id, $position + strlen( $amp_prefix ) );
```
Comment (pradeep910) [inline rthistory-with-ga.php]: For the ids which store as `amp-xxxx` we use full string as client ID, I think this will only store `xxxx` and not `amp-xxxx`. 

If `amp-xxxx` is found in client id, just use it as it is.

Comment (sagarnasit) [reply rthistory-with-ga.php]: Fixed this.
